[package]
name = "viewer-types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "COSMIC Viewer shared types"

[dependencies]
shared = { path = "../shared" }
serde.workspace = true
